default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost
  # user: ""
  # password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 10

development:
  <<: *default
  database: 'lcbo_api_developent' # <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>
